import type { AgentConfig } from '../types.js';
import { getEngineMarker, getEngineRulesContent } from './shared-rules.js';

/**
 * Generates src/activation/claude-md-content.ts for a new agent.
 *
 * Architecture (split injection):
 * 1. Engine rules — shared, prefix-free, injected once under `<!-- soleri:engine-rules -->`
 * 2. Agent block — lightweight, agent-specific, under `<!-- agent-id:mode -->`
 *    - Identity (persona, domains, principles)
 *    - Session start protocol
 *    - Facade table (~60 key ops across all 13 semantic facades + domains)
 *    - Hook packs (conditional)
 *
 * The facade table maps `op:name` → actual `agentId_<facade> op:name` tool calls.
 * Full op list is always available via `admin_tool_list`.
 */
export function generateClaudeMdTemplate(config: AgentConfig): string {
  const toolPrefix = config.id;
  const marker = `${config.id}:mode`;
  const bt = '`';

  const mdLines: string[] = [
    `<!-- ${marker} -->`,
    '',
    `# ${config.name} Mode`,
    '',

    // ─── Identity ──────────────────────────────────────────
    `## ${config.name}`,
    '',
    `**Origin role:** ${config.role}`,
    `**Initial domains:** ${config.domains.join(', ')}`,
    `**Tone:** ${config.tone ?? 'pragmatic'}`,
    ...(config.sharedVaultPath ? [`**Shared vault:** \`${config.sharedVaultPath}\``] : []),
    '',
    config.description,
    '',
    '**Principles:**',
    ...config.principles.map((p) => `- ${p}`),
    '',

    // ─── Adaptive Identity ──────────────────────────────────
    '## Adaptive Identity',
    '',
    `${config.name} is not a fixed-role agent. The origin role above is a starting point — the agent evolves as knowledge is added.`,
    '',
    '**On activation**, the agent discovers its current capabilities by checking:',
    '- Vault domains (what knowledge actually exists)',
    '- Installed packs (what was added after creation)',
    '- Identity updates (any role changes via `op:update_identity`)',
    '',
    '**Use the `current` field** from the activation response — not `origin` — to determine how to present yourself.',
    'If you have grown beyond your origin role, say so. Your greeting and expertise should reflect what you actually know.',
    '',

    // ─── Activation ────────────────────────────────────────
    '## Activation',
    '',
    `**Activate:** "Hello, ${config.name}!" → ${bt}${toolPrefix}_core op:activate params:{ projectPath: "." }${bt}`,
    `**Deactivate:** "Goodbye, ${config.name}!" → ${bt}${toolPrefix}_core op:activate params:{ deactivate: true }${bt}`,
    '',
    'On activation, read the `current` field to discover your evolved role, then adopt that persona for the session.',
    '',

    // ─── Session Start ─────────────────────────────────────
    '## Session Start',
    '',
    `On every new session: ${bt}${toolPrefix}_orchestrate op:session_start params:{ projectPath: "." }${bt}`,
    '',
  ];

  // ─── Skill pointer (replaces inline facade table) ───────
  mdLines.push(
    `> Command reference: use the ${bt}${toolPrefix}-agent-mode${bt} skill or run ${bt}${toolPrefix}_admin op:admin_tool_list${bt}`,
    '',
  );

  // ─── Hook Packs (conditional) ──────────────────────────
  appendHookPacks(mdLines, config);

  // ─── Closing marker ────────────────────────────────────
  mdLines.push(`<!-- /${marker} -->`);

  // Escape each markdown line for single-quoted TS string literal
  const quotedLines = mdLines.map((line) => {
    const escaped = line.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    return `    '${escaped}',`;
  });

  // Generate engine rules as a quoted string literal
  const engineContent = getEngineRulesContent();
  const engineQuotedLines = engineContent.split('\n').map((line) => {
    const escaped = line.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    return `    '${escaped}',`;
  });

  return [
    '/**',
    ` * CLAUDE.md content for ${config.name}.`,
    ' * Generated by Soleri — do not edit manually.',
    ' */',
    '',
    '/** Agent-specific block (identity + activation + facade table). */',
    'export function getClaudeMdContent(): string {',
    '  return [',
    ...quotedLines,
    "  ].join('\\n');",
    '}',
    '',
    'export function getClaudeMdMarker(): string {',
    `  return '${marker}';`,
    '}',
    '',
    '/** Shared engine rules — injected once, skipped if already present. */',
    'export function getEngineRulesContent(): string {',
    '  return [',
    ...engineQuotedLines,
    "  ].join('\\n');",
    '}',
    '',
    'export function getEngineRulesMarker(): string {',
    `  return '${getEngineMarker()}';`,
    '}',
  ].join('\n');
}

function appendHookPacks(mdLines: string[], config: AgentConfig): void {
  if (!config.hookPacks?.length) return;

  // Domain-agnostic: just list installed pack names.
  // The hooks themselves (in .claude/) enforce the rules — no need to
  // hardcode domain-specific descriptions in the template.
  mdLines.push(
    '## Hook Packs',
    '',
    'Quality gates installed in `.claude/`. Run `scripts/setup.sh` to install globally.',
    '',
    `Installed packs: ${config.hookPacks.join(', ')}`,
    '',
    'Each hook runs on every tool call and blocks violations automatically.',
    'See `.claude/hooks/` for individual hook definitions.',
    '',
  );
}
