import type { AgentConfig } from '../types.js';
import { getSharedRules } from './shared-rules.js';

/**
 * Generates src/activation/claude-md-content.ts for a new agent.
 *
 * Architecture:
 * 1. Agent-specific identity (persona, domains, principles)
 * 2. Session start protocol
 * 3. Curated facade table (~30 key ops, grouped by category)
 * 4. Shared behavioral rules (vault-first, planning, output formatting)
 * 5. Hook packs (conditional)
 *
 * Full op list is always available via `admin_tool_list` — no need to
 * enumerate all 145+ ops in CLAUDE.md.
 */
export function generateClaudeMdTemplate(config: AgentConfig): string {
  const toolPrefix = config.id;
  const marker = `${config.id}:mode`;
  const bt = '`';

  const mdLines: string[] = [
    `<!-- ${marker} -->`,
    '',
    `# ${config.name} Mode`,
    '',

    // ─── Identity ──────────────────────────────────────────
    `## ${config.name}`,
    '',
    `**Role:** ${config.role}`,
    `**Domains:** ${config.domains.join(', ')}`,
    `**Tone:** ${config.tone ?? 'pragmatic'}`,
    '',
    config.description,
    '',
    '**Principles:**',
    ...config.principles.map((p) => `- ${p}`),
    '',

    // ─── Activation ────────────────────────────────────────
    '## Activation',
    '',
    `**Activate:** "Hello, ${config.name}!" → ${bt}${toolPrefix}_core op:activate params:{ projectPath: "." }${bt}`,
    `**Deactivate:** "Goodbye, ${config.name}!" → ${bt}${toolPrefix}_core op:activate params:{ deactivate: true }${bt}`,
    '',
    'On activation, adopt the returned persona. Stay in character until deactivated.',
    '',

    // ─── Session Start ─────────────────────────────────────
    '## Session Start',
    '',
    `On every new session: ${bt}${toolPrefix}_core op:register params:{ projectPath: "." }${bt}`,
    '',
  ];

  // ─── Compact Facade Table ───────────────────────────────
  mdLines.push(
    '## Essential Tools',
    `<!-- ${toolPrefix}:tools -->`,
    '',
    '| Facade | Key Ops |',
    '|--------|---------|',
    `| ${bt}${toolPrefix}_core${bt} | ${bt}health${bt}, ${bt}search${bt}, ${bt}identity${bt}, ${bt}register${bt}, ${bt}activate${bt} |`,
  );

  // Domain facades — one row per domain
  for (const d of config.domains) {
    const toolName = `${toolPrefix}_${d.replace(/-/g, '_')}`;
    mdLines.push(
      `| ${bt}${toolName}${bt} | ${bt}get_patterns${bt}, ${bt}search${bt}, ${bt}capture${bt} |`,
    );
  }

  // Engine facades — compact, grouped by concern
  mdLines.push(
    `| ${bt}${toolPrefix}_core${bt} (vault) | ${bt}search_intelligent${bt}, ${bt}capture_knowledge${bt}, ${bt}capture_quick${bt}, ${bt}search_feedback${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (memory) | ${bt}memory_search${bt}, ${bt}memory_capture${bt}, ${bt}session_capture${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (planning) | ${bt}create_plan${bt}, ${bt}approve_plan${bt}, ${bt}plan_split${bt}, ${bt}plan_reconcile${bt}, ${bt}plan_complete_lifecycle${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (orchestrate) | ${bt}orchestrate_plan${bt}, ${bt}orchestrate_execute${bt}, ${bt}orchestrate_complete${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (brain) | ${bt}brain_stats${bt}, ${bt}brain_feedback${bt}, ${bt}rebuild_vocabulary${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (control) | ${bt}route_intent${bt}, ${bt}morph${bt}, ${bt}get_behavior_rules${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (loop) | ${bt}loop_start${bt}, ${bt}loop_iterate${bt}, ${bt}loop_status${bt}, ${bt}loop_cancel${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (governance) | ${bt}governance_dashboard${bt}, ${bt}governance_policy${bt}, ${bt}governance_proposals${bt} |`,
    `| ${bt}${toolPrefix}_core${bt} (admin) | ${bt}admin_health${bt}, ${bt}admin_tool_list${bt}, ${bt}admin_diagnostic${bt} |`,
  );

  mdLines.push('', `> Full list: ${bt}${toolPrefix}_core op:admin_tool_list${bt}`, '');

  // ─── Shared Behavioral Rules ───────────────────────────
  mdLines.push(...getSharedRules(toolPrefix));

  // ─── Hook Packs (conditional) ──────────────────────────
  appendHookPacks(mdLines, config);

  // ─── Closing marker ────────────────────────────────────
  mdLines.push(`<!-- /${marker} -->`);

  // Escape each markdown line for single-quoted TS string literal
  const quotedLines = mdLines.map((line) => {
    const escaped = line.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
    return `    '${escaped}',`;
  });

  return [
    '/**',
    ` * CLAUDE.md content for ${config.name}.`,
    ' * Generated by Soleri — do not edit manually.',
    ' */',
    'export function getClaudeMdContent(): string {',
    '  return [',
    ...quotedLines,
    "  ].join('\\n');",
    '}',
    '',
    'export function getClaudeMdMarker(): string {',
    `  return '${marker}';`,
    '}',
  ].join('\n');
}

function appendHookPacks(mdLines: string[], config: AgentConfig): void {
  if (!config.hookPacks?.length) return;

  // Domain-agnostic: just list installed pack names.
  // The hooks themselves (in .claude/) enforce the rules — no need to
  // hardcode domain-specific descriptions in the template.
  mdLines.push(
    '## Hook Packs',
    '',
    'Quality gates installed in `.claude/`. Run `scripts/setup.sh` to install globally.',
    '',
    `Installed packs: ${config.hookPacks.join(', ')}`,
    '',
    'Each hook runs on every tool call and blocks violations automatically.',
    'See `.claude/hooks/` for individual hook definitions.',
    '',
  );
}
