import type { AgentConfig } from '../types.js';

/**
 * Generates src/activation/inject-claude-md.ts for a new agent.
 * Provides idempotent project-level CLAUDE.md / AGENTS.md injection —
 * creates, appends, or updates the agent's section between HTML comment
 * markers.
 *
 * Global (~/.claude/CLAUDE.md) injection is NOT handled here; it is owned
 * by the engine's scaffoldGlobalClaudeMd() (in @soleri/core skills/sync-skills.ts)
 * and runs during skill sync. Keeping the responsibility in one place
 * prevents double-writes and dangling legacy blocks.
 *
 * Uses array-joined pattern because the generated code contains
 * template literals (backticks) for path operations and string interpolation.
 */
export function generateInjectClaudeMd(config: AgentConfig): string {
  const marker = `${config.id}:mode`;

  return [
    "import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';",
    "import { join } from 'node:path';",
    "import { homedir } from 'node:os';",
    "import { getClaudeMdContent, getClaudeMdMarker, getEngineRulesContent, getEngineRulesMarker } from './claude-md-content.js';",
    '',
    'export interface InjectResult {',
    '  injected: boolean;',
    '  path: string;',
    "  action: 'created' | 'updated' | 'appended';",
    '  engineRules?: boolean;',
    '}',
    '',
    '/**',
    ' * Inject a marker-delimited block into a file.',
    ' * If the marker already exists, replaces the content between markers.',
    ' * Otherwise appends (or creates the file).',
    ' */',
    "function injectBlock(filePath: string, content: string, marker: string): 'created' | 'updated' | 'appended' | 'skipped' {",
    `  const startMarker = '<!-- ' + marker + ' -->';`,
    `  const endMarker = '<!-- /' + marker + ' -->';`,
    '',
    '  if (!existsSync(filePath)) {',
    "    writeFileSync(filePath, content + '\\n', 'utf-8');",
    "    return 'created';",
    '  }',
    '',
    "  const existing = readFileSync(filePath, 'utf-8');",
    '',
    '  if (existing.includes(startMarker)) {',
    '    const startIdx = existing.indexOf(startMarker);',
    '    const endIdx = existing.indexOf(endMarker);',
    '    if (endIdx !== -1) {',
    '      const currentBlock = existing.slice(startIdx, endIdx + endMarker.length);',
    "      if (currentBlock === content.trim()) return 'skipped';",
    '    }',
    '    if (endIdx === -1) {',
    "      const updated = existing.slice(0, startIdx) + content + '\\n' + existing.slice(startIdx + startMarker.length);",
    "      writeFileSync(filePath, updated, 'utf-8');",
    "      return 'updated';",
    '    }',
    '    const updated = existing.slice(0, startIdx) + content + existing.slice(endIdx + endMarker.length);',
    "    writeFileSync(filePath, updated, 'utf-8');",
    "    return 'updated';",
    '  }',
    '',
    "  const separator = existing.endsWith('\\n') ? '\\n' : '\\n\\n';",
    "  writeFileSync(filePath, existing + separator + content + '\\n', 'utf-8');",
    "  return 'appended';",
    '}',
    '',
    '/**',
    ' * Inject engine rules + agent block into a CLAUDE.md file.',
    ' *',
    ' * Engine rules (shared, prefix-free) are injected ONCE under',
    ' * `<!-- soleri:engine-rules -->`. If already present, they are updated.',
    ' * Agent block (identity + facade table) is injected under',
    ` * \`<!-- ${marker} -->\`.`,
    ' *',
    ' * @param skipEngineRules - If true, skip engine rules injection (used for global files)',
    ' */',
    'function injectIntoFile(filePath: string, skipEngineRules = false): InjectResult {',
    '  // Step 1: Engine rules — shared across all agents (skip for global files)',
    '  let engineAction: string = "skipped";',
    '  if (!skipEngineRules) {',
    '    engineAction = injectBlock(filePath, getEngineRulesContent(), getEngineRulesMarker());',
    '  }',
    '',
    '  // Step 2: Agent-specific block',
    '  const agentAction = injectBlock(filePath, getClaudeMdContent(), getClaudeMdMarker());',
    '',
    '  return {',
    '    injected: true,',
    '    path: filePath,',
    "    action: agentAction === 'skipped' ? 'appended' : agentAction,",
    "    engineRules: engineAction !== 'skipped',",
    '  };',
    '}',
    '',
    '/**',
    ' * Inject agent CLAUDE.md section into a project.',
    ' * - Engine rules: injected once, updated if already present',
    ' * - Agent block: created, updated, or appended',
    ' */',
    'export function injectClaudeMd(projectPath: string): InjectResult {',
    "  return injectIntoFile(join(projectPath, 'CLAUDE.md'));",
    '}',
    '',
    '/**',
    ' * Remove a marker-delimited block from a file.',
    ' */',
    'function removeBlock(filePath: string, marker: string): boolean {',
    '  if (!existsSync(filePath)) return false;',
    "  const existing = readFileSync(filePath, 'utf-8');",
    `  const startMarker = '<!-- ' + marker + ' -->';`,
    `  const endMarker = '<!-- /' + marker + ' -->';`,
    '  const startIdx = existing.indexOf(startMarker);',
    '  if (startIdx === -1) return false;',
    '  const endIdx = existing.indexOf(endMarker);',
    '  if (endIdx === -1) return false;',
    "  const before = existing.slice(0, startIdx).replace(/\\n+$/, '');",
    "  const after = existing.slice(endIdx + endMarker.length).replace(/^\\n+/, '');",
    "  const cleaned = before + (before && after ? '\\n\\n' : '') + after;",
    "  writeFileSync(filePath, cleaned || '', 'utf-8');",
    '  return true;',
    '}',
    '',
    '/**',
    ' * Remove agent section from a project CLAUDE.md.',
    ' */',
    'export function removeClaudeMd(projectPath: string): { removed: boolean; path: string } {',
    "  const filePath = join(projectPath, 'CLAUDE.md');",
    '  return { removed: removeBlock(filePath, getClaudeMdMarker()), path: filePath };',
    '}',
    '',
    '/**',
    ' * Remove shared engine rules from a file.',
    ' * Use only when NO agents remain in the file.',
    ' */',
    'export function removeEngineRules(filePath: string): boolean {',
    '  return removeBlock(filePath, getEngineRulesMarker());',
    '}',
    '',
    '/**',
    ' * Check if the agent marker exists in a CLAUDE.md file.',
    ' */',
    'export function hasAgentMarker(filePath: string): boolean {',
    '  if (!existsSync(filePath)) return false;',
    "  const content = readFileSync(filePath, 'utf-8');",
    `  return content.includes('<!-- ${marker} -->');`,
    '}',
    '',
    '/**',
    ' * Check if engine rules are already present in a CLAUDE.md file.',
    ' */',
    'export function hasEngineRules(filePath: string): boolean {',
    '  if (!existsSync(filePath)) return false;',
    "  const content = readFileSync(filePath, 'utf-8');",
    "  return content.includes('<!-- ' + getEngineRulesMarker() + ' -->');",
    '}',
    '',
    '// ─── AGENTS.md support (OpenCode, Codex) ──────────────────────',
    '',
    '/**',
    ' * Inject agent sections into a project AGENTS.md.',
    ' * Same engine rules + agent block as CLAUDE.md, targeting AGENTS.md instead.',
    ' * OpenCode reads AGENTS.md as its primary instruction file.',
    ' */',
    'export function injectAgentsMd(projectPath: string): InjectResult {',
    "  return injectIntoFile(join(projectPath, 'AGENTS.md'));",
    '}',
    '',
    '/**',
    ' * Remove agent section from a project AGENTS.md.',
    ' */',
    'export function removeAgentsMd(projectPath: string): { removed: boolean; path: string } {',
    "  const filePath = join(projectPath, 'AGENTS.md');",
    '  return { removed: removeBlock(filePath, getClaudeMdMarker()), path: filePath };',
    '}',
    '',
    '/**',
    ' * Check if the agent marker exists in an AGENTS.md file.',
    ' */',
    'export function hasAgentMarkerInAgentsMd(filePath: string): boolean {',
    '  if (!existsSync(filePath)) return false;',
    "  const content = readFileSync(filePath, 'utf-8');",
    `  return content.includes('<!-- ${marker} -->');`,
    '}',
    '',
    '// ─── Global variants (inject into home directory) ──────────────',
    '',
    '/**',
    ' * Inject agent sections into the global ~/.claude/CLAUDE.md.',
    ' */',
    'export function injectClaudeMdGlobal(): InjectResult {',
    "  const globalDir = join(homedir(), '.claude');",
    '  mkdirSync(globalDir, { recursive: true });',
    "  return injectIntoFile(join(globalDir, 'CLAUDE.md'));",
    '}',
    '',
    '/**',
    ' * Remove agent section from the global ~/.claude/CLAUDE.md.',
    ' */',
    'export function removeClaudeMdGlobal(): { removed: boolean; path: string } {',
    "  const filePath = join(homedir(), '.claude', 'CLAUDE.md');",
    '  return { removed: removeBlock(filePath, getClaudeMdMarker()), path: filePath };',
    '}',
    '',
    '/**',
    ' * Inject agent sections into the global ~/.config/opencode/AGENTS.md.',
    ' */',
    'export function injectAgentsMdGlobal(): InjectResult {',
    "  const globalDir = join(homedir(), '.config', 'opencode');",
    '  mkdirSync(globalDir, { recursive: true });',
    "  return injectIntoFile(join(globalDir, 'AGENTS.md'));",
    '}',
  ].join('\n');
}
