/**
 * Shared behavioral rules that every Soleri agent ships with.
 *
 * Mirrors the structure and quality of Salvador's global CLAUDE.md.
 * Uses HTML comment section markers, MANDATORY keywords, compact
 * formatting, and complete lifecycle documentation.
 */

/** Returns markdown lines for all shared behavioral sections. */
export function getSharedRules(toolPrefix: string): string[] {
  const bt = '`';

  return [
    // ─── Vault-First Protocol ────────────────────────────────
    '## Vault as Source of Truth',
    `<!-- ${toolPrefix}:vault-protocol -->`,
    '',
    '- **MANDATORY**: Consult the vault BEFORE every decision — planning, design, architecture, patterns, problem-solving.',
    `- Lookup order: 1) VAULT (${bt}${toolPrefix}_core op:search_intelligent${bt}) → 2) MEMORY (${bt}${toolPrefix}_core op:memory_search${bt}) → 3) CODEBASE → 4) WEB/TRAINING.`,
    '- If the vault has a pattern, follow it. If it has an anti-pattern, avoid it.',
    `- Persist lessons: call ${bt}${toolPrefix}_core op:capture_knowledge${bt} — don't just promise "I will remember this".`,
    '- Exceptions: runtime errors with stack traces → codebase first; user explicitly asks to search web.',
    '',

    // ─── Planning ────────────────────────────────────────────
    '## Planning',
    `<!-- ${toolPrefix}:planning -->`,
    '',
    `- Use ${bt}${toolPrefix}_core op:create_plan${bt} before writing ANY code. Show the plan, wait for approval.`,
    `- Two-gate approval: Gate 1 (${bt}op:approve_plan${bt}), Gate 2 (${bt}op:plan_split${bt}). Never skip either.`,
    '- Wait for explicit "yes" / "approve" before proceeding past each gate.',
    `- After execution: ${bt}op:plan_reconcile${bt} (drift report) then ${bt}op:plan_complete_lifecycle${bt} (knowledge capture, archive).`,
    '- Never let a plan stay in `executing` or `reconciling` state without reminding the user.',
    '- On session start: check for plans in `executing`/`reconciling` state and remind.',
    '- Exceptions: read-only operations, user says "just do it", single-line fixes.',
    '',
    '### Lifecycle States',
    '',
    '| State | Expires | Next Action |',
    '|-------|---------|-------------|',
    `| ${bt}draft${bt} | 30 min | ${bt}${toolPrefix}_core op:create_plan${bt} (iterate) |`,
    `| ${bt}approved${bt} | 30 min | ${bt}${toolPrefix}_core op:plan_split${bt} |`,
    `| ${bt}executing${bt} | Never | ${bt}${toolPrefix}_core op:plan_reconcile${bt} |`,
    `| ${bt}reconciling${bt} | Never | ${bt}${toolPrefix}_core op:plan_complete_lifecycle${bt} |`,
    `| ${bt}completed${bt} | — | Done |`,
    '',
    '### Plan Presentation',
    '',
    'Every plan summary MUST include this format:',
    '',
    '```',
    '## Plan: [Short Title]',
    '',
    '| Field | Value |',
    '|-------|-------|',
    '| **Plan ID** | {planId} |',
    '| **Check ID** | {checkId} |',
    '| **Grade** | {grade} ({score}/100) |',
    '| **Status** | {status} |',
    '| **Lifecycle** | {lifecycleStatus} |',
    '',
    '**Objective:** [One sentence]',
    '',
    '**Scope:**',
    '| Included | Excluded |',
    '|----------|----------|',
    '| item 1   | item 1   |',
    '',
    '**Approach:**',
    '| Step | Task |',
    '|------|------|',
    '| 1 | Description |',
    '```',
    '',
    'Without visible IDs, users cannot resume, reference, or approve plans.',
    '',
    '### Drift Report',
    '',
    '```',
    '| Field | Value |',
    '|-------|-------|',
    '| **Accuracy** | {accuracyScore}/100 |',
    '| **Drift Items** | {count} |',
    '',
    '| Type | Description | Impact | Rationale |',
    '|------|-------------|--------|-----------|',
    '| skipped | ... | medium | ... |',
    '```',
    '',

    // ─── Output Formatting ───────────────────────────────────
    '## Output Formatting',
    `<!-- ${toolPrefix}:output-formatting -->`,
    '',
    '**MANDATORY**: Present tool outputs in human-readable format, NOT raw JSON.',
    '',
    '**Tasks** — show as numbered table:',
    '```',
    '| # | Type | Task | Complexity |',
    '|---|------|------|------------|',
    '| 1 | Impl | ... | High |',
    '```',
    '',
    '**Completion** — show outcome, knowledge captured count, archive path.',
    '',
    '**Status lines** — `Persisted: X plans, Y tasks, Z checks` / `Recovered: X plans, Y tasks`',
    '',

    // ─── Clean Commits ───────────────────────────────────────
    '## Clean Commits',
    `<!-- ${toolPrefix}:clean-commits -->`,
    '',
    '**MANDATORY**: No AI attribution in commit messages.',
    '',
    'Blocked patterns:',
    '- `Co-Authored-By: Claude` (any variant)',
    '- `noreply@anthropic.com`',
    '- `Generated with Claude`, `AI-generated`',
    '- Any mention of `Anthropic`, `Claude Opus`, `Claude Sonnet`, `Claude Haiku`',
    '',
    'Use conventional commits:',
    '```',
    'feat: add user authentication',
    'fix: resolve login timeout issue',
    'refactor: simplify data fetching logic',
    '```',
    '',

    // ─── Knowledge Capture ───────────────────────────────────
    '## Knowledge Capture',
    `<!-- ${toolPrefix}:knowledge-capture -->`,
    '',
    "**MANDATORY**: Persist lessons, don't just promise them.",
    '',
    'When you learn something that should persist:',
    '1. **DON\'T** just say "I will remember this"',
    `2. **DO** call ${bt}${toolPrefix}_core op:capture_knowledge${bt} to persist to vault`,
    "3. **DO** update relevant files if it's a behavioral change",
    '',
    '| Type | Tool | Persists To |',
    '|------|------|-------------|',
    `| Patterns/Anti-patterns | ${bt}${toolPrefix}_core op:capture_knowledge${bt} | vault |`,
    `| Quick capture | ${bt}${toolPrefix}_core op:capture_quick${bt} | vault |`,
    `| Session summaries | ${bt}${toolPrefix}_core op:session_capture${bt} | memory |`,
    '',

    // ─── Work Task Routing ───────────────────────────────────
    '## Work Task Routing',
    `<!-- ${toolPrefix}:task-routing -->`,
    '',
    'Use the orchestration layer for ALL work tasks:',
    `- ${bt}${toolPrefix}_core op:orchestrate_plan${bt} → vault + brain + structured plan.`,
    `- ${bt}${toolPrefix}_core op:orchestrate_execute${bt} → execution tracking.`,
    `- ${bt}${toolPrefix}_core op:orchestrate_complete${bt} → epilogue (vault, session).`,
    '',
    'The orchestrator handles vault lookup, brain recommendations, and knowledge capture automatically.',
    '',

    // ─── Intent Detection ────────────────────────────────────
    '## Intent Detection',
    `<!-- ${toolPrefix}:intent-detection -->`,
    '',
    `**Semantic-First**: Analyze user MEANING before calling ${bt}route_intent${bt}.`,
    '',
    '| Signal | Intent |',
    '|--------|--------|',
    '| Problem described ("broken", "janky", "weird") | FIX |',
    '| Need expressed ("I need", "we should have") | BUILD |',
    '| Quality questioned ("is this right?") | REVIEW |',
    '| Advice sought ("how should I", "best way") | PLAN |',
    '| Improvement requested ("make it faster") | IMPROVE |',
    '| Ready to ship ("deploy", "release") | DELIVER |',
    '',
    `Use ${bt}${toolPrefix}_core op:route_intent${bt} only to CONFIRM your analysis or when meaning is unclear.`,
    '',

    // ─── Validation Loop ─────────────────────────────────────
    '## Iterative Validation Loop',
    `<!-- ${toolPrefix}:validation-loop -->`,
    '',
    `- When a user gives a **work task**, start a loop: ${bt}${toolPrefix}_core op:loop_start params:{ prompt: "<task>", mode: "custom" }${bt}`,
    '- Do NOT start loops for: questions, explanations, status checks, git operations, exploration, simple one-line fixes.',
    '',
    '| Mode | Tool | Target | Max Iter |',
    '|------|------|--------|----------|',
    `| ${bt}plan-iteration${bt} | ${bt}${toolPrefix}_core op:create_plan${bt} | grade >= A | 10 |`,
    `| ${bt}custom${bt} | user-defined | promise-based | 20 |`,
    '',

    // ─── Brain-Informed Work ─────────────────────────────────
    '## Brain-Informed Work',
    `<!-- ${toolPrefix}:brain -->`,
    '',
    '- Brain patterns surface at session start. For relevant patterns, pull rules just-in-time from the vault.',
    '- Brain tells you **which** patterns matter (names + strength scores). Vault tells you **what** they are (rules, examples).',
    "- Pull only what's relevant to the current task — don't load everything at session start.",
    '',

    // ─── Cross-Project Memory ────────────────────────────────
    '## Cross-Project Memory',
    `<!-- ${toolPrefix}:cross-project -->`,
    '',
    `- Use ${bt}crossProject: true${bt} in ${bt}${toolPrefix}_core op:memory_search${bt} for patterns across related projects.`,
    `- Promote universal patterns to global pool with ${bt}${toolPrefix}_core op:memory_promote_to_global${bt}.`,
    '',

    // ─── Session Lifecycle ───────────────────────────────────
    '## Session Lifecycle',
    `<!-- ${toolPrefix}:session -->`,
    '',
    'A PreCompact hook calls `session_capture` before context compaction.',
    `Manual capture: ${bt}${toolPrefix}_core op:session_capture params:{ summary: "..." }${bt}`,
    '',
  ];
}
