/**
 * Template: Telegram supervisor — process management with restart and logging.
 * Generated by @soleri/forge for agents with Telegram transport.
 */

import type { AgentConfig } from '../types.js';

export function generateTelegramSupervisor(config: AgentConfig): string {
  return `/**
 * ${config.name} — Telegram Bot Supervisor.
 * Generated by @soleri/forge.
 *
 * Wraps the bot process with:
 * - Restart on crash (exponential backoff)
 * - Restart on self-update (exit code 75)
 * - Graceful shutdown (SIGINT/SIGTERM)
 * - Log rotation
 */

import { spawn } from 'node:child_process';
import { mkdirSync, appendFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const LOG_DIR = join(homedir(), '.${config.id}', 'logs');
const MAX_LOG_AGE_DAYS = 7;
const SELF_UPDATE_EXIT_CODE = 75;

// Exponential backoff: 1s, 2s, 4s, 8s, 16s, 30s max
const MIN_RESTART_DELAY = 1000;
const MAX_RESTART_DELAY = 30_000;

let restartCount = 0;
let shutdownRequested = false;

function log(message: string): void {
  const ts = new Date().toISOString();
  const line = \`[\${ts}] [supervisor] \${message}\`;
  console.log(line);
  try {
    mkdirSync(LOG_DIR, { recursive: true });
    const date = ts.split('T')[0];
    appendFileSync(join(LOG_DIR, \`telegram-\${date}.log\`), line + '\\n', 'utf-8');
  } catch {
    // Log write failure is non-critical
  }
}

function rotateLogs(): void {
  try {
    const cutoff = Date.now() - MAX_LOG_AGE_DAYS * 24 * 60 * 60 * 1000;
    const files = readdirSync(LOG_DIR);
    for (const file of files) {
      if (!file.startsWith('telegram-') && !file.startsWith('events-')) continue;
      const filePath = join(LOG_DIR, file);
      try {
        const stat = statSync(filePath);
        if (stat.mtimeMs < cutoff) {
          rmSync(filePath);
          log(\`Rotated old log: \${file}\`);
        }
      } catch {
        // Skip files we can't stat
      }
    }
  } catch {
    // Rotation failure is non-critical
  }
}

function getRestartDelay(): number {
  const delay = Math.min(MIN_RESTART_DELAY * Math.pow(2, restartCount), MAX_RESTART_DELAY);
  return delay;
}

function startBot(): void {
  rotateLogs();
  log(\`Starting bot (attempt \${restartCount + 1})...\`);

  const child = spawn('node', [join(process.cwd(), 'dist', 'telegram-bot.js')], {
    stdio: 'inherit',
    env: { ...process.env },
  });

  child.on('exit', (code, signal) => {
    if (shutdownRequested) {
      log('Bot stopped (shutdown requested).');
      process.exit(0);
    }

    if (code === SELF_UPDATE_EXIT_CODE) {
      log('Bot requested self-update restart. Rebuilding...');
      restartCount = 0;
      try {
        const { execFileSync } = require('node:child_process');
        execFileSync('npm', ['run', 'build'], { cwd: process.cwd(), stdio: 'pipe', timeout: 60_000 });
        log('Rebuild succeeded. Restarting...');
      } catch (buildErr: unknown) {
        const buildMsg = buildErr instanceof Error ? buildErr.message : String(buildErr);
        log(\`Rebuild failed: \${buildMsg}. Attempting rollback...\`);
        try {
          const { execFileSync: execFile2 } = require('node:child_process');
          execFile2('git', ['revert', 'HEAD', '--no-edit'], { cwd: process.cwd(), stdio: 'pipe', timeout: 30_000 });
          execFile2('npm', ['run', 'build'], { cwd: process.cwd(), stdio: 'pipe', timeout: 60_000 });
          log('Rollback succeeded. Restarting with previous code...');
        } catch {
          log('Rollback also failed. Restarting with current code anyway...');
        }
      }
      setTimeout(startBot, 1000);
      return;
    }

    if (code === 0) {
      log('Bot exited cleanly.');
      process.exit(0);
    }

    restartCount++;
    const delay = getRestartDelay();
    log(\`Bot exited with code \${code ?? signal}. Restarting in \${delay}ms...\`);
    setTimeout(startBot, delay);
  });

  child.on('error', (err) => {
    log(\`Failed to start bot: \${err.message}\`);
    restartCount++;
    const delay = getRestartDelay();
    setTimeout(startBot, delay);
  });

  // Reset backoff after 60 seconds of successful running
  setTimeout(() => {
    if (!shutdownRequested) restartCount = 0;
  }, 60_000);
}

// Graceful shutdown
process.on('SIGINT', () => {
  shutdownRequested = true;
  log('SIGINT received, shutting down...');
});
process.on('SIGTERM', () => {
  shutdownRequested = true;
  log('SIGTERM received, shutting down...');
});

startBot();
`;
}
