/**
 * Template: Telegram agent loop — wires @soleri/core agent loop to MCP tools.
 * Generated by @soleri/forge for agents with Telegram transport.
 */

import type { AgentConfig } from '../types.js';

export function generateTelegramAgent(config: AgentConfig): string {
  return `/**
 * ${config.name} — Telegram Agent Loop.
 * Generated by @soleri/forge.
 *
 * Wires the @soleri/core agent loop to the agent's MCP tools.
 */

import {
  runAgentLoop,
  McpToolBridge,
  createOutputCompressor,
} from '@soleri/core';
import type {
  ChatMessage,
  AgentLoopResult,
  AgentCallbacks,
  McpToolRegistration,
} from '@soleri/core';
import type { TelegramConfig } from './telegram-config.js';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

// ─── Core Tools ──────────────────────────────────────────────────────

const CORE_TOOLS: McpToolRegistration[] = [
  {
    name: 'bash',
    description: 'Execute a shell command. Returns stdout/stderr.',
    inputSchema: {
      type: 'object',
      properties: {
        command: { type: 'string', description: 'Shell command to execute.' },
        timeout: { type: 'number', description: 'Timeout in ms. Default: 120000.' },
      },
      required: ['command'],
    },
    handler: async (input) => {
      try {
        const timeout = (input.timeout as number) ?? 120_000;
        const output = execFileSync('/bin/sh', ['-c', input.command as string], {
          timeout,
          encoding: 'utf-8',
          maxBuffer: 1024 * 1024,
        });
        return output;
      } catch (err: unknown) {
        const error = err as { stdout?: string; stderr?: string; message?: string };
        return \`Error: \${error.stderr ?? error.stdout ?? error.message ?? 'Unknown error'}\`;
      }
    },
  },
  {
    name: 'read_file',
    description: 'Read a file from the filesystem.',
    inputSchema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'File path to read.' },
      },
      required: ['path'],
    },
    handler: async (input) => {
      return readFileSync(input.path as string, 'utf-8');
    },
  },
  {
    name: 'write_file',
    description: 'Write content to a file.',
    inputSchema: {
      type: 'object',
      properties: {
        path: { type: 'string', description: 'File path to write.' },
        content: { type: 'string', description: 'Content to write.' },
      },
      required: ['path', 'content'],
    },
    handler: async (input) => {
      mkdirSync(dirname(input.path as string), { recursive: true });
      writeFileSync(input.path as string, input.content as string, 'utf-8');
      return \`Wrote \${(input.content as string).length} bytes to \${input.path}\`;
    },
  },
  {
    name: 'glob',
    description: 'Find files matching a glob pattern.',
    inputSchema: {
      type: 'object',
      properties: {
        pattern: { type: 'string', description: 'Glob pattern.' },
        cwd: { type: 'string', description: 'Working directory.' },
      },
      required: ['pattern'],
    },
    handler: async (input) => {
      const cwd = (input.cwd as string) ?? process.cwd();
      const output = execFileSync('find', ['.', '-path', input.pattern as string, '-type', 'f'], {
        cwd,
        encoding: 'utf-8',
        timeout: 10_000,
      });
      const lines = output.trim().split('\\n').filter(Boolean).slice(0, 100);
      return lines.length > 0 ? lines.join('\\n') : 'No files found.';
    },
  },
  {
    name: 'grep',
    description: 'Search file contents with regex.',
    inputSchema: {
      type: 'object',
      properties: {
        pattern: { type: 'string', description: 'Regex pattern.' },
        path: { type: 'string', description: 'File or directory to search.' },
        type: { type: 'string', description: 'File type filter (e.g., ts, js).' },
      },
      required: ['pattern'],
    },
    handler: async (input) => {
      const searchPath = (input.path as string) ?? '.';
      const args = ['--no-heading', '-n', input.pattern as string, searchPath];
      if (input.type) args.splice(2, 0, '--type', input.type as string);
      try {
        const output = execFileSync('rg', args, {
          encoding: 'utf-8',
          timeout: 10_000,
        });
        const lines = output.trim().split('\\n').filter(Boolean).slice(0, 50);
        return lines.length > 0 ? lines.join('\\n') : 'No matches found.';
      } catch {
        return 'No matches found.';
      }
    },
  },
];

// ─── Agent Factory ───────────────────────────────────────────────────

export interface TelegramAgentRunner {
  run(messages: ChatMessage[], callbacks?: AgentCallbacks): Promise<AgentLoopResult>;
  registerTool(tool: McpToolRegistration): void;
  getToolCount(): number;
}

export function createTelegramAgent(config: TelegramConfig): TelegramAgentRunner {
  const bridge = new McpToolBridge({
    compressor: createOutputCompressor({ maxLength: 4000 }),
    maxOutput: 10_000,
  });

  // Register core tools
  bridge.registerAll(CORE_TOOLS);

  const systemPrompt = buildSystemPrompt(config);

  return {
    run: async (messages: ChatMessage[], callbacks?: AgentCallbacks) => {
      return runAgentLoop(messages, {
        apiKey: config.apiKey,
        model: config.model,
        systemPrompt,
        tools: bridge.getTools(),
        executor: bridge.createExecutor(),
        maxIterations: config.maxIterations,
        maxTokens: config.maxTokens,
      }, callbacks);
    },

    registerTool: (tool: McpToolRegistration) => {
      bridge.register(tool);
    },

    getToolCount: () => bridge.size,
  };
}

// ─── System Prompt ───────────────────────────────────────────────────

function buildSystemPrompt(config: TelegramConfig): string {
  const parts: string[] = [
    '# ${config.name}',
    '',
    '${config.role}',
    '',
    '## Environment',
    \`- Platform: \${process.platform}\`,
    \`- Working directory: \${config.workingDirectory ?? process.cwd()}\`,
    \`- Date: \${new Date().toISOString().split('T')[0]}\`,
    '',
    '## Telegram Formatting',
    '- Keep responses concise (under 2000 chars when possible)',
    '- Use Markdown: **bold**, *italic*, \\\`code\\\`, \\\`\\\`\\\`code blocks\\\`\\\`\\\`',
    '- Use bullet points for lists',
    '- No raw JSON in responses — format for human reading',
    '',
    '## Available Tools',
    '- bash: Execute shell commands',
    '- read_file: Read file contents',
    '- write_file: Write to files',
    '- glob: Find files by pattern',
    '- grep: Search file contents',
  ];

  return parts.join('\\n');
}
`;
}
