/**
 * Template: Telegram bot entry point with Grammy.
 * Generated by @soleri/forge for agents with Telegram transport.
 */

import type { AgentConfig } from '../types.js';

export function generateTelegramBot(config: AgentConfig): string {
  return `/**
 * ${config.name} — Telegram Bot Entry Point.
 * Generated by @soleri/forge.
 *
 * Grammy bot with middleware pipeline, session management, and agent dispatch.
 */

import { Bot } from 'grammy';
import { loadTelegramConfig, type TelegramConfig } from './telegram-config.js';
import { createTelegramAgent } from './telegram-agent.js';
import {
  ChatSessionManager,
  ChatAuthManager,
  FragmentBuffer,
  chunkResponse,
} from '@soleri/core';
import type { Fragment } from '@soleri/core';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { mkdirSync, appendFileSync } from 'node:fs';

// ─── Config ──────────────────────────────────────────────────────────

const CONFIG_DIR = join(homedir(), '.${config.id}');
const SESSIONS_DIR = join(CONFIG_DIR, 'telegram-sessions');
const AUTH_FILE = join(CONFIG_DIR, 'telegram-auth.json');
const LOG_DIR = join(CONFIG_DIR, 'logs');

// ─── State ───────────────────────────────────────────────────────────

const processingLocks = new Set<string>();
let telegramConfig: TelegramConfig;
let sessions: ChatSessionManager;
let auth: ChatAuthManager;
let fragmentBuffer: FragmentBuffer;

// ─── Event Logger ────────────────────────────────────────────────────

function logEvent(type: string, chatId: number | string, data?: Record<string, unknown>): void {
  try {
    mkdirSync(LOG_DIR, { recursive: true });
    const date = new Date().toISOString().split('T')[0];
    const entry = JSON.stringify({ ts: new Date().toISOString(), chatId, type, ...data });
    appendFileSync(join(LOG_DIR, \`events-\${date}.jsonl\`), entry + '\\n', 'utf-8');
  } catch {
    // Logging failure is non-critical
  }
}

// ─── Bot Setup ───────────────────────────────────────────────────────

export async function startBot(): Promise<void> {
  telegramConfig = loadTelegramConfig();

  // Initialize infrastructure
  sessions = new ChatSessionManager({
    storageDir: SESSIONS_DIR,
    ttlMs: 7_200_000, // 2 hours
    compactionThreshold: 100,
    compactionKeep: 40,
  });
  sessions.startReaper();

  auth = new ChatAuthManager({
    storagePath: AUTH_FILE,
    passphrase: telegramConfig.passphrase,
    allowedUsers: telegramConfig.allowedUsers,
  });

  fragmentBuffer = new FragmentBuffer(
    { startThreshold: 4000, maxGapMs: 1500, maxParts: 12, maxTotalBytes: 50_000 },
    (key, merged) => handleMergedMessage(key, merged),
  );

  const bot = new Bot(telegramConfig.botToken);

  // ─── Commands ──────────────────────────────────────────────────

  bot.command('start', async (ctx) => {
    if (!checkAuth(ctx)) return;
    await ctx.reply('Welcome! I am ${config.name}, ${config.role}. How can I help?');
    logEvent('command', ctx.chat.id, { command: 'start' });
  });

  bot.command('clear', async (ctx) => {
    if (!checkAuth(ctx)) return;
    sessions.clear(String(ctx.chat.id));
    await ctx.reply('Session cleared. Starting fresh.');
    logEvent('command', ctx.chat.id, { command: 'clear' });
  });

  bot.command('health', async (ctx) => {
    if (!checkAuth(ctx)) return;
    const status = {
      sessions: sessions.size,
      authenticated: auth.authenticatedCount,
      fragments: fragmentBuffer.pendingCount,
    };
    await ctx.reply(\`Health: \${JSON.stringify(status, null, 2)}\`);
    logEvent('command', ctx.chat.id, { command: 'health' });
  });

  bot.command('help', async (ctx) => {
    if (!checkAuth(ctx)) return;
    await ctx.reply(
      [
        '<b>Commands:</b>',
        '/start — Initialize',
        '/clear — Clear conversation',
        '/health — System status',
        '/help — This message',
        '/stop — Cancel current task',
      ].join('\\n'),
      { parse_mode: 'HTML' },
    );
  });

  bot.command('stop', async (ctx) => {
    const chatId = String(ctx.chat.id);
    if (processingLocks.has(chatId)) {
      // Cancellation is handled via AbortController in telegram-agent
      await ctx.reply('Stopping current task...');
      logEvent('command', ctx.chat.id, { command: 'stop' });
    } else {
      await ctx.reply('No task is currently running.');
    }
  });

  // ─── Text Messages ────────────────────────────────────────────

  bot.on('message:text', async (ctx) => {
    const text = ctx.message.text;
    const chatId = String(ctx.chat.id);
    const userId = ctx.from?.id;

    // Auth check — if passphrase is set, check if user is authenticated
    if (auth.enabled && !auth.isAuthenticated(String(userId))) {
      if (telegramConfig.passphrase && text === telegramConfig.passphrase) {
        auth.authenticate(String(userId), text);
        await ctx.reply('Authenticated! How can I help?');
        logEvent('auth', ctx.chat.id, { userId });
        return;
      }
      await ctx.reply('Please authenticate first.');
      return;
    }

    logEvent('message_in', ctx.chat.id, { length: text.length });

    // Fragment buffering
    const fragment: Fragment = {
      text,
      messageId: ctx.message.message_id,
      receivedAt: Date.now(),
    };

    const buffered = fragmentBuffer.receive(chatId, fragment);
    if (buffered) return; // Wait for more fragments

    // Process immediately
    await dispatchToAgent(chatId, text, ctx);
  });

  // ─── Error Handling ───────────────────────────────────────────

  bot.catch((err) => {
    console.error('[bot] Error:', err.message);
    logEvent('error', 'global', { error: err.message });
  });

  // ─── Start ────────────────────────────────────────────────────

  console.log('[${config.id}] Starting Telegram bot...');
  logEvent('bot_start', 'system');

  process.on('SIGINT', () => shutdown(bot));
  process.on('SIGTERM', () => shutdown(bot));

  await bot.start();
}

// ─── Agent Dispatch ──────────────────────────────────────────────────

async function dispatchToAgent(
  chatId: string,
  text: string,
  ctx: { reply: (text: string, options?: Record<string, unknown>) => Promise<unknown> },
): Promise<void> {
  if (processingLocks.has(chatId)) {
    await ctx.reply('I am still working on your previous request. Please wait.');
    return;
  }

  processingLocks.add(chatId);

  try {
    // Append user message
    sessions.appendMessage(chatId, {
      role: 'user',
      content: text,
      timestamp: Date.now(),
    });

    // Run agent
    const agent = createTelegramAgent(telegramConfig);
    const session = sessions.getOrCreate(chatId);
    const result = await agent.run(session.messages);

    // Append agent response
    sessions.appendMessages(chatId, result.newMessages);

    // Send response in chunks
    const chunks = chunkResponse(result.text, { maxChunkSize: 4000, format: 'html' });
    for (const chunk of chunks) {
      try {
        await ctx.reply(chunk, { parse_mode: 'HTML' });
      } catch {
        // Fallback to plain text if HTML fails
        await ctx.reply(chunk);
      }
    }

    logEvent('response_out', chatId, {
      iterations: result.iterations,
      toolCalls: result.toolCalls,
      chunks: chunks.length,
    });
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(\`[agent] Error for chat \${chatId}:\`, msg);
    await ctx.reply('Sorry, I encountered an error. Please try again.');
    logEvent('error', chatId, { error: msg });
  } finally {
    processingLocks.delete(chatId);
  }
}

// ─── Fragment Handler ────────────────────────────────────────────────

function handleMergedMessage(key: string, merged: string): void {
  // key is the chatId — dispatch the merged text
  // Note: we don't have the ctx here, so we use the bot API directly
  // In a real implementation, you'd store the ctx reference
  console.log(\`[fragment] Merged \${merged.length} chars for \${key}\`);
}

// ─── Auth Helper ─────────────────────────────────────────────────────

function checkAuth(ctx: { from?: { id: number }; reply: (text: string) => Promise<unknown> }): boolean {
  if (!auth.enabled) return true;
  if (auth.isAuthenticated(String(ctx.from?.id))) return true;
  ctx.reply('Please authenticate first.');
  return false;
}

// ─── Shutdown ────────────────────────────────────────────────────────

function shutdown(bot: Bot): void {
  console.log('[${config.id}] Shutting down...');
  logEvent('bot_stop', 'system');
  fragmentBuffer.close();
  sessions.close();
  bot.stop();
  process.exit(0);
}

// ─── Main ────────────────────────────────────────────────────────────

startBot().catch((err) => {
  console.error('[${config.id}] Fatal:', err);
  process.exit(1);
});
`;
}
