/**
 * Template: Telegram configuration module.
 * Generated by @soleri/forge for agents with Telegram transport.
 */

import type { AgentConfig } from '../types.js';

export function generateTelegramConfig(config: AgentConfig): string {
  return `/**
 * Telegram Configuration — env + file-based config loading.
 * Generated by @soleri/forge.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

export interface TelegramConfig {
  /** Telegram bot token (from @BotFather). */
  botToken: string;
  /** Anthropic API key. */
  apiKey: string;
  /** Claude model to use. Default: 'claude-sonnet-4-20250514'. */
  model?: string;
  /** Working directory for the agent. Default: cwd. */
  workingDirectory?: string;
  /** Allowed user IDs (empty = any authenticated user). */
  allowedUsers?: number[];
  /** Auth passphrase. If unset, auth is disabled. */
  passphrase?: string;
  /** Max output tokens per LLM call. Default: 16384. */
  maxTokens?: number;
  /** Max agent loop iterations. Default: 200. */
  maxIterations?: number;
}

const CONFIG_DIR = join(homedir(), '.${config.id}');
const CONFIG_FILE = join(CONFIG_DIR, 'telegram.json');

/**
 * Load Telegram config from environment variables and config file.
 * Environment variables take priority over file-based config.
 */
export function loadTelegramConfig(): TelegramConfig {
  let fileConfig: Partial<TelegramConfig> = {};

  if (existsSync(CONFIG_FILE)) {
    try {
      fileConfig = JSON.parse(readFileSync(CONFIG_FILE, 'utf-8'));
    } catch {
      console.error('[config] Failed to parse telegram.json, using defaults');
    }
  }

  const botToken = process.env.TELEGRAM_BOT_TOKEN ?? fileConfig.botToken ?? '';
  const apiKey =
    process.env.ANTHROPIC_API_KEY ?? fileConfig.apiKey ?? '';

  if (!botToken) {
    throw new Error(
      'Missing TELEGRAM_BOT_TOKEN. Set via environment or ~/.${config.id}/telegram.json',
    );
  }
  if (!apiKey) {
    throw new Error(
      'Missing ANTHROPIC_API_KEY. Set via environment or ~/.${config.id}/telegram.json',
    );
  }

  return {
    botToken,
    apiKey,
    model: process.env.ANTHROPIC_MODEL ?? fileConfig.model ?? 'claude-sonnet-4-20250514',
    workingDirectory:
      process.env.AGENT_WORKING_DIR ?? fileConfig.workingDirectory ?? process.cwd(),
    allowedUsers: fileConfig.allowedUsers ?? [],
    passphrase: fileConfig.passphrase,
    maxTokens: fileConfig.maxTokens ?? 16384,
    maxIterations: fileConfig.maxIterations ?? 200,
  };
}
`;
}
