import type { Locale } from '../types';

export const homeContent = (locale: Locale) => content[locale];

const content: Record<Locale, HomeContent> = {
  en: {
    heroTitle:
      'Build a <span class="accent-amber">second brain</span> that <span class="accent-teal">remembers</span> everything and <span class="accent-green">gets smarter</span> over time.',
    heroText: 'Your knowledge, structured and searchable. Context that compounds across every session, every project.',
    principleTitle: 'Your expertise should compound — not evaporate.',
    compareBeforeLabel: 'Without memory',
    compareAfterLabel: 'With Soleri',
    compareBefore: `<span class="dim">// Session 1</span>
<span class="warn">You:</span> We use Tailwind with semantic tokens,
      never raw hex. Spacing is 4px base.
<span class="warn">AI:</span>  Got it! I'll follow that.

<span class="dim">// Session 2 — next day</span>
<span class="warn">You:</span> Why did you use #3B82F6 again?
<span class="warn">AI:</span>  Sorry, can you remind me of your
      color conventions?

<span class="dim">// Session 47 — same question, again</span>`,
    compareAfter: `<span class="dim">// Session 1</span>
<span class="hl">You:</span> We use Tailwind with semantic tokens.
<span class="hl">AI:</span>  Captured to vault. I'll enforce this.

<span class="dim">// Session 47</span>
<span class="hl">You:</span> Review this component.
<span class="hl">AI:</span>  <span class="ok">✓ Session briefing: 2 active plans, 3 patterns relevant</span>
      Found 2 raw hex values. Vault says: semantic only.
      <span class="ok">✓ Pattern applied from vault</span>
      <span class="ok">✓ Radar: auto-captured anti-pattern from correction</span>`,
    howTitle: 'Your second brain.<br/>Always learning.<br/>Never forgets.',
    howText:
      'A <strong>Vault</strong> for long-term memory, a <strong>Brain</strong> that learns what works, a <strong>Radar</strong> that detects patterns automatically, and <strong>Agency</strong> that suggests actions before you ask. 270+ ops. Feed it knowledge — it compounds.',
    engineTags: ['Vault', 'Brain', 'Radar', 'Agency'],
    features: [
      {
        title: 'Your brain, as code',
        text: 'One command creates your second brain. Domains, rules, workflows — all declarative, all version-controlled.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pluggable knowledge packs',
        text: 'npm packages you snap into any agent. Starter and community packs ship free.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">built-in</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installed</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installed</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">shared vault</span>`,
      },
      {
        title: 'A folder is all you need',
        text: 'Your second brain is a folder. Plain files. No build step. Your AI editor reads it natively. The engine handles memory, learning, and intelligence.',
        code: `<span class="key">my-brain/</span>            <span class="cmt"># your second brain</span>
├── <span class="ok">agent.yaml</span>        <span class="cmt"># what do I know</span>
├── <span class="key">instructions/</span>     <span class="cmt"># how I think</span>
├── <span class="key">workflows/</span>        <span class="cmt"># how I work</span>
├── <span class="key">knowledge/</span>        <span class="cmt"># what I've learned</span>
├── <span class="key">skills/</span>           <span class="cmt"># what I can do</span>
└── .mcp.json         <span class="cmt"># connects to engine</span>`,
      },
      {
        title: 'Starts smart, gets smarter',
        text: 'Starter knowledge on create. Learning Radar detects patterns from your corrections and search misses — captures silently, no interruptions.',
        code: `<span class="cmt">$ npx soleri create my-brain</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># While you work:</span>
<span class="ok">Radar:</span> Detected anti-pattern from your correction.
       <span class="val">Auto-captured with tag: radar-detected</span>
<span class="ok">Radar:</span> "caching patterns" searched 3× with 0 results.
       <span class="val">Knowledge gap flagged for review.</span>`,
      },
    ],
    cardsTitle: 'One brain. Many domains.',
    cards: [
      {
        title: 'Frontend',
        domain: 'Domain',
        cls: 'salvador',
        capabilities: ['React patterns', 'Design tokens', 'Component review', 'Accessibility'],
        ships: 'Ask about buttons — the vault searches here first.',
      },
      {
        title: 'Backend',
        domain: 'Domain',
        cls: 'gaudi',
        capabilities: ['API conventions', 'Database schemas', 'Auth patterns', 'Performance'],
        ships: 'Ask about queries or API design — the vault pulls from here.',
      },
      {
        title: 'Cross-cutting',
        domain: 'Domain',
        cls: 'sentinel',
        capabilities: ['Git workflows', 'Code review', 'Testing strategies', 'Documentation'],
        ships: 'Patterns that span domains. The graph finds connections automatically.',
      },
    ],
    terminalTitle: 'Terminal',
    terminalCode: `<span class="comment"># Build your second brain (~3 seconds)</span>
<span class="prompt">$</span> <span class="cmd">npx soleri create</span> <span class="arg">my-brain</span>

<span class="comment">  ✓ Created agent.yaml</span>
<span class="comment">  ✓ Generated instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ Ready — no build step needed</span>

<span class="comment"># Connect and start</span>
<span class="prompt">$</span> <span class="cmd">npx soleri install</span>        <span class="comment"># connect to your editor</span>
<span class="prompt">$</span> <span class="cmd">npx soleri dev</span>            <span class="comment"># start the engine</span>

<span class="comment">  Session briefing: 46 entries, 0 active plans</span>
<span class="comment">  Brain: ready (270+ ops)</span>
<span class="comment">  OAuth: Claude Code token discovered ✓</span>`,
    archTitle: 'Two layers, one second brain',
    archSubtitle:
      'Your files define what it knows. The engine makes it learn. They evolve independently.',
    layers: [
      {
        label: 'Agent Folder',
        text: 'Plain files: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Your AI editor reads them natively. No TypeScript, no build step.',
      },
      {
        label: 'Domain Packs',
        text: 'Pluggable expertise modules. Add design system science, code review, or custom domains without changing the agent folder.',
      },
      {
        label: 'Knowledge Engine',
        text: 'Single MCP server (<code>@soleri/core</code>). Vault, Brain, Curator, Planner, Memory, Agency, Learning Radar. 270+ ops. Persistent state and learning. Auto-discovers Claude Code OAuth for free Anthropic API.',
      },
      {
        label: 'Transports',
        text: 'MCP (stdio) for any AI coding editor. HTTP/SSE for dashboards. WebSocket for streaming. Telegram for conversational access.',
      },
    ],
  },
  uk: {
    heroTitle:
      'Побудуй <span class="accent-amber">другий мозок</span>, який <span class="accent-teal">пам\'ятає</span> все і <span class="accent-green">розумнішає</span> з часом.',
    heroText:
      'Твої знання, структуровані та пошукові. Контекст, що накопичується з кожною сесією, кожним проєктом.',
    principleTitle: 'Твоя експертиза має накопичуватися — а не випаровуватися.',
    compareBeforeLabel: "Без пам'яті",
    compareAfterLabel: 'Із Soleri',
    compareBefore: `<span class="dim">// Сесія 1</span>
<span class="warn">Ти:</span> Ми використовуємо Tailwind із семантичними токенами,
      ніколи — сирі hex. Базовий крок відступів — 4px.
<span class="warn">AI:</span>  Зрозуміло! Я цього дотримуватимуся.

<span class="dim">// Сесія 2 — наступного дня</span>
<span class="warn">Ти:</span> Чому ти знову використав #3B82F6?
<span class="warn">AI:</span>  Вибач, можеш нагадати мені
      твої домовленості щодо кольорів?

<span class="dim">// Сесія 47 — те саме питання, знову</span>`,
    compareAfter: `<span class="dim">// Сесія 1</span>
<span class="hl">Ти:</span> Ми використовуємо Tailwind із семантичними токенами.
<span class="hl">AI:</span>  Збережено у сховищі. Я це проконтролюю.

<span class="dim">// Сесія 47</span>
<span class="hl">Ти:</span> Переглянь цей компонент.
<span class="hl">AI:</span>  Знайдено 2 сирі hex-значення. У твоєму сховищі зазначено:
      лише семантичні токени. Виправляю.
      <span class="ok">✓ Шаблон застосовано зі сховища</span>
      <span class="ok">✓ Brain strength: 94% (12 сесій)</span>`,
    howTitle: 'Твій другий мозок.<br/>Завжди навчається.<br/>Ніколи не забуває.',
    howText:
      '<strong>Сховище</strong> для довготривалої пам\'яті, <strong>Brain</strong> для навчання того, що працює, <strong>Memory</strong> що переноситься між сесіями та проєктами. Годуй знаннями — вони накопичуються.',
    engineTags: ['Сховище', 'Brain', 'Memory'],
    features: [
      {
        title: 'Конфігурація як код',
        text: 'Одна команда генерує конфіг. Голос, домени, бекенди сховища — усе декларативно й під контролем версій.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Підключувані пакети знань',
        text: 'npm-пакети, які можна підключити до будь-якого агента. Стартовий та спільнотний пакети безкоштовні.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">вбудовано</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">встановлено</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">встановлено</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">спільне сховище</span>`,
      },
      {
        title: 'Тека = агент',
        text: 'Агент — це тека. Без TypeScript, без збірки. Ваш AI-редактор читає їх напряму. Рушій забезпечує збереження та навчання.',
        code: `<span class="key">my-agent/</span>           <span class="cmt"># агент — це тека</span>
├── <span class="ok">agent.yaml</span>       <span class="cmt"># ідентичність + конфіг</span>
├── <span class="key">instructions/</span>    <span class="cmt"># правила поведінки</span>
├── <span class="key">workflows/</span>       <span class="cmt"># покрокові плейбуки</span>
├── <span class="key">knowledge/</span>       <span class="cmt"># доменні знання</span>
├── <span class="key">skills/</span>          <span class="cmt"># файли SKILL.md</span>
└── .mcp.json        <span class="cmt"># підключення до рушія</span>`,
      },
      {
        title: 'Холодний старт, а не з нуля',
        text: 'Стартові знання — під час create. Сканування проєкту — під час першого запуску. Далі — керована фіксація.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Auto-captured                <span class="val">12 patterns</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># After 3 sessions:</span>
<span class="warn">Brain:</span> You've fixed this import style 3×.
       <span class="val">Capture as pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Один мозок. Багато доменів.',
    cards: [
      {
        title: 'Фронтенд',
        domain: 'Домен',
        cls: 'salvador',
        capabilities: ['Патерни React', 'Токени дизайну', "Рев'ю компонентів", 'Доступність'],
        ships: 'Запитай про кнопки — сховище спершу шукає тут.',
      },
      {
        title: 'Бекенд',
        domain: 'Домен',
        cls: 'gaudi',
        capabilities: [
          'Конвенції API',
          'Схеми бази даних',
          'Патерни автентифікації',
          'Продуктивність',
        ],
        ships: 'Запитай про запити чи дизайн API — сховище підтягує звідси.',
      },
      {
        title: 'Наскрізні',
        domain: 'Домен',
        cls: 'sentinel',
        capabilities: ['Робочі процеси Git', "Код-рев'ю", 'Стратегії тестування', 'Документація'],
        ships: "Патерни, що охоплюють домени. Граф автоматично знаходить зв'язки.",
      },
    ],
    terminalTitle: 'Термінал',
    terminalCode: `<span class="comment"># Створення файлового агента (~3 секунди)</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Створено agent.yaml</span>
<span class="comment">  ✓ Згенеровано instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ Автоматично зібрано CLAUDE.md</span>
<span class="comment">  ✓ Готово — без етапу збірки</span>

<span class="comment"># Реєстрація та старт розробки</span>
<span class="prompt">$</span> <span class="cmd">soleri install</span>            <span class="comment"># реєстрація MCP-сервера</span>
<span class="prompt">$</span> <span class="cmd">soleri dev</span>                <span class="comment"># запуск рушія + спостереження за файлами</span>

<span class="comment"># Додайте ще знань</span>
<span class="prompt">$</span> <span class="cmd">soleri pack</span> <span class="arg">install community/react-patterns</span>`,
    archTitle: 'Два шари, чітко розділені',
    archSubtitle:
      'Тека агента — це оболонка. Рушій знань — це мозок. Вони розвиваються незалежно.',
    layers: [
      {
        label: 'Тека агента',
        text: 'Прості файли: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Ваш AI-редактор читає їх напряму. Без TypeScript, без збірки.',
      },
      {
        label: 'Доменні пакети',
        text: 'Підключувані модулі експертизи. Додавай дизайн-системи, код-рев\'ю або власні домени без зміни теки агента.',
      },
      {
        label: 'Рушій знань',
        text: 'Один MCP-сервер (<code>@soleri/core</code>). Сховище, Brain, Куратор, Планувальник, Пам\'ять. Персистентний стан та навчання. Усі агенти використовують один рушій.',
      },
      {
        label: 'Транспорти',
        text: 'MCP (stdio) для будь-якого AI-редактора. HTTP/SSE для дашбордів. WebSocket для стримінгу. Telegram для розмовного доступу.',
      },
    ],
  },
  it: {
    heroTitle:
      'Costruisci un <span class="accent-amber">secondo cervello</span> che <span class="accent-teal">ricorda</span> tutto e <span class="accent-green">diventa più intelligente</span> nel tempo.',
    heroText:
      'La tua conoscenza, strutturata e ricercabile. Contesto che si accumula in ogni sessione, ogni progetto.',
    principleTitle: 'La tua competenza dovrebbe accumularsi, non evaporare.',
    compareBeforeLabel: 'Senza memoria',
    compareAfterLabel: 'Con Soleri',
    compareBefore: `<span class="dim">// Sessione 1</span>
<span class="warn">Tu:</span> Usiamo Tailwind con token semantici, mai esadecimale puro. Lo spazio è base 4px.
<span class="warn">AI:</span> Capito! Seguirò questo.

<span class="dim">// Sessione 2 — il giorno seguente</span>
<span class="warn">Tu:</span> Perché hai usato di nuovo #3B82F6?
<span class="warn">AI:</span> Scusa, puoi ricordarmi le tue convenzioni sui colori?

<span class="dim">// Sessione 47 — stessa domanda, ancora una volta</span>`,
    compareAfter: `<span class="dim">// Sessione 1</span>
<span class="hl">Tu:</span> Usiamo Tailwind con token semantici.
<span class="hl">AI:</span> Salvato nel Vault. D'ora in poi applicherò questa regola.

<span class="dim">// Sessione 47</span>
<span class="hl">Tu:</span> Rivedi questo componente.
<span class="hl">AI:</span> Ho trovato 2 valori esadecimali grezzi. Il Vault dice: solo token semantici. Correggo subito.
      <span class="ok">✓ Pattern applicato dal Vault</span>
      <span class="ok">✓ Brain strength: 94% (12 sessioni)</span>`,
    howTitle: 'Il tuo secondo cervello.<br/>Sempre in apprendimento.<br/>Non dimentica mai.',
    howText:
      'Un <strong>Vault</strong> per la memoria a lungo termine, un <strong>Cervello</strong> che impara cosa funziona, una <strong>Memoria</strong> che si mantiene tra sessioni e progetti. Dagli conoscenza — si accumula.',
    engineTags: ['Vault', 'Cervello', 'Memoria'],
    features: [
      {
        title: 'Configurazione come codice',
        text: 'Un comando genera la configurazione. Voce, domini, backend del vault — tutto dichiarativo, tutto sotto controllo di versione.',
        code: `<span class="cmt"># agent.yaml (generato da create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">diretto, tecnico, approfondito</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastruttura]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pacchetti di conoscenza modulari',
        text: 'Pacchetti npm che inserisci in qualsiasi agente. I pacchetti Starter e Community sono gratuiti.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">integrato</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installato</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installato</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">vault condiviso</span>`,
      },
      {
        title: 'Cartella = agente',
        text: "Un agente è una cartella. Niente TypeScript, nessun passaggio di build. Il tuo editor AI lo legge nativamente. Il motore fornisce persistenza e apprendimento.",
        code: `<span class="key">my-agent/</span>           <span class="cmt"># l'agente È la cartella</span>
├── <span class="ok">agent.yaml</span>       <span class="cmt"># identità + configurazione</span>
├── <span class="key">instructions/</span>    <span class="cmt"># regole comportamentali</span>
├── <span class="key">workflows/</span>       <span class="cmt"># playbook passo-passo</span>
├── <span class="key">knowledge/</span>       <span class="cmt"># intelligenza di dominio</span>
├── <span class="key">skills/</span>          <span class="cmt"># file SKILL.md</span>
└── .mcp.json        <span class="cmt"># connessione al motore</span>`,
      },
      {
        title: 'Avvio a freddo, non una lavagna vuota',
        text: "Conoscenza iniziale alla creazione. Scansione del progetto al primo avvio. Poi ti guida nell'onboarding.",
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Conoscenza iniziale installata  <span class="val">34 pattern</span>
<span class="ok">✓</span> Progetto scansionato              <span class="val">React + TS</span>
<span class="ok">✓</span> Acquisizione automatica                <span class="val">12 pattern</span>
<span class="ok">✓</span> Vault pronto                  <span class="val">46 voci</span>

<span class="cmt"># Dopo 3 sessioni:</span>
<span class="warn">Cervello:</span> Hai corretto questo stile di importazione 3 volte.
       <span class="val">Acquisire come pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Un cervello. Molti domini.',
    cards: [
      {
        title: 'Frontend',
        domain: 'Dominio',
        cls: 'salvador',
        capabilities: ['Pattern React', 'Token di design', 'Revisione componenti', 'Accessibilità'],
        ships: 'Chiedi dei pulsanti — il vault cerca qui per primo.',
      },
      {
        title: 'Backend',
        domain: 'Dominio',
        cls: 'gaudi',
        capabilities: [
          'Convenzioni API',
          'Schemi database',
          'Pattern di autenticazione',
          'Prestazioni',
        ],
        ships: 'Chiedi di query o API design — il vault attinge da qui.',
      },
      {
        title: 'Trasversali',
        domain: 'Dominio',
        cls: 'sentinel',
        capabilities: [
          'Flussi di lavoro Git',
          'Revisione del codice',
          'Strategie di test',
          'Documentazione',
        ],
        ships: 'Pattern che attraversano i domini. Il grafo trova connessioni automaticamente.',
      },
    ],
    terminalTitle: 'Terminale',
    terminalCode: `<span class="comment"># Crea un agente file-tree (~3 secondi)</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Creato agent.yaml</span>
<span class="comment">  ✓ Generati instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ CLAUDE.md composto automaticamente</span>
<span class="comment">  ✓ Pronto — nessun passaggio di build</span>

<span class="comment"># Registra e inizia a sviluppare</span>
<span class="prompt">$</span> <span class="cmd">soleri install</span>            <span class="comment"># registra server MCP</span>
<span class="prompt">$</span> <span class="cmd">soleri dev</span>                <span class="comment"># avvia motore + osserva file</span>

<span class="comment"># Alimentalo con più conoscenza</span>
<span class="prompt">$</span> <span class="cmd">soleri pack</span> <span class="arg">install community/react-patterns</span>`,
    archTitle: 'Due livelli, nettamente separati',
    archSubtitle:
      "La cartella dell'agente è il guscio. Il motore di conoscenza è il cervello. Evolvono indipendentemente.",
    layers: [
      {
        label: 'Cartella agente',
        text: 'File semplici: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Il tuo editor AI li legge nativamente. Niente TypeScript, nessun build.',
      },
      {
        label: 'Pacchetti dominio',
        text: "Moduli di competenza collegabili. Aggiungi design system, code review o domini personalizzati senza modificare la cartella dell'agente.",
      },
      {
        label: 'Motore di conoscenza',
        text: 'Un unico server MCP (<code>@soleri/core</code>). Vault, Cervello, Curatore, Pianificatore, Memoria. Stato persistente e apprendimento. Tutti gli agenti condividono un motore.',
      },
      {
        label: 'Trasporti',
        text: 'MCP (stdio) per qualsiasi editor AI. HTTP/SSE per dashboard. WebSocket per streaming. Telegram per accesso conversazionale.',
      },
    ],
  },
};

interface HomeContent {
  heroTitle: string;
  heroText: string;
  principleTitle: string;
  compareBeforeLabel: string;
  compareAfterLabel: string;
  compareBefore: string;
  compareAfter: string;
  howTitle: string;
  howText: string;
  engineTags: string[];
  features: { title: string; text: string; code: string }[];
  cardsTitle: string;
  cards: { title: string; domain: string; cls: string; capabilities: string[]; ships: string }[];
  terminalTitle: string;
  terminalCode: string;
  archTitle: string;
  archSubtitle: string;
  layers: { label: string; text: string }[];
}
