import type { Locale } from '../types';

export const homeContent = (locale: Locale) => content[locale];

const content: Record<Locale, HomeContent> = {
  en: {
    heroTitle:
      'What you <span class="accent-amber">teach</span> it <span class="accent-teal">stays</span>. What it <span class="accent-green">learns</span> compounds.',
    heroText: 'Persistent memory. Structured knowledge. Context that carries across every session.',
    principleTitle: 'Knowledge should compound — not evaporate.',
    compareBeforeLabel: 'Without memory',
    compareAfterLabel: 'With Soleri',
    compareBefore: `<span class="dim">// Session 1</span>
<span class="warn">You:</span> We use Tailwind with semantic tokens,
      never raw hex. Spacing is 4px base.
<span class="warn">AI:</span>  Got it! I'll follow that.

<span class="dim">// Session 2 — next day</span>
<span class="warn">You:</span> Why did you use #3B82F6 again?
<span class="warn">AI:</span>  Sorry, can you remind me of your
      color conventions?

<span class="dim">// Session 47 — same question, again</span>`,
    compareAfter: `<span class="dim">// Session 1</span>
<span class="hl">You:</span> We use Tailwind with semantic tokens.
<span class="hl">AI:</span>  Captured to vault. I'll enforce this.

<span class="dim">// Session 47</span>
<span class="hl">You:</span> Review this component.
<span class="hl">AI:</span>  Found 2 raw hex values. Your vault says
      semantic tokens only. Fixing now.
      <span class="ok">✓ Pattern applied from vault</span>
      <span class="ok">✓ Brain strength: 94% (12 sessions)</span>`,
    howTitle: 'One engine.<br/>One vault.<br/>No coordination overhead.',
    howText:
      'A <strong>Vault</strong> for knowledge, a <strong>Brain</strong> that learns, <strong>Memory</strong> that persists. Single process. Feed it knowledge — it organizes, vectorizes, and learns.',
    engineTags: ['Vault', 'Brain', 'Memory'],
    features: [
      {
        title: 'Configuration as code',
        text: 'One command generates the config. Voice, domains, vault backends — all declarative, all version-controlled.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pluggable knowledge packs',
        text: 'npm packages you snap into any agent. Starter and community packs ship free.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">built-in</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installed</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installed</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">shared vault</span>`,
      },
      {
        title: 'File tree = agent',
        text: 'An agent is a folder. No TypeScript, no build step. Claude Code reads it natively. The engine provides persistence and learning.',
        code: `<span class="key">my-agent/</span>           <span class="cmt"># the agent IS the folder</span>
├── <span class="ok">agent.yaml</span>       <span class="cmt"># identity + config</span>
├── <span class="key">instructions/</span>    <span class="cmt"># behavioral rules</span>
├── <span class="key">workflows/</span>       <span class="cmt"># step-by-step playbooks</span>
├── <span class="key">knowledge/</span>       <span class="cmt"># domain intelligence</span>
├── <span class="key">skills/</span>          <span class="cmt"># SKILL.md files</span>
└── .mcp.json        <span class="cmt"># connects to engine</span>`,
      },
      {
        title: 'Cold start, not blank slate',
        text: 'Starter knowledge on create. Project scan on first run. Guided capture as you work.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Auto-captured                <span class="val">12 patterns</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># After 3 sessions:</span>
<span class="warn">Brain:</span> You've fixed this import style 3×.
       <span class="val">Capture as pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'One vault. Many domains.',
    cards: [
      {
        title: 'Frontend',
        domain: 'Domain',
        cls: 'salvador',
        capabilities: ['React patterns', 'Design tokens', 'Component review', 'Accessibility'],
        ships: 'Ask about buttons — the vault searches here first.',
      },
      {
        title: 'Backend',
        domain: 'Domain',
        cls: 'gaudi',
        capabilities: ['API conventions', 'Database schemas', 'Auth patterns', 'Performance'],
        ships: 'Ask about queries or API design — the vault pulls from here.',
      },
      {
        title: 'Cross-cutting',
        domain: 'Domain',
        cls: 'sentinel',
        capabilities: ['Git workflows', 'Code review', 'Testing strategies', 'Documentation'],
        ships: 'Patterns that span domains. The graph finds connections automatically.',
      },
    ],
    terminalTitle: 'Terminal',
    terminalCode: `<span class="comment"># Create a file-tree agent (~3 seconds)</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Created agent.yaml</span>
<span class="comment">  ✓ Generated instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ Auto-composed CLAUDE.md</span>
<span class="comment">  ✓ Ready to use — no build step needed</span>

<span class="comment"># Register and start developing</span>
<span class="prompt">$</span> <span class="cmd">soleri install</span>            <span class="comment"># register MCP server</span>
<span class="prompt">$</span> <span class="cmd">soleri dev</span>                <span class="comment"># start engine + watch files</span>

<span class="comment"># Feed it more knowledge</span>
<span class="prompt">$</span> <span class="cmd">soleri pack</span> <span class="arg">install community/react-patterns</span>`,
    archTitle: 'Two layers, cleanly separated',
    archSubtitle:
      'The agent folder is the shell. The knowledge engine is the brain. They evolve independently.',
    layers: [
      {
        label: 'Agent Folder',
        text: 'Plain files: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Claude Code reads them natively. No TypeScript, no build step.',
      },
      {
        label: 'Domain Packs',
        text: 'Pluggable expertise modules. Add design system science, code review, or custom domains without changing the agent folder.',
      },
      {
        label: 'Knowledge Engine',
        text: 'Single MCP server (<code>@soleri/core</code>). Vault, Brain, Curator, Planner, Memory. Persistent state and learning. All agents share one engine.',
      },
      {
        label: 'Transports',
        text: 'MCP (stdio) for Claude Code and Cursor. HTTP/SSE for dashboards. WebSocket for streaming. Telegram for conversational access.',
      },
    ],
  },
  uk: {
    heroTitle:
      '<span class="accent-amber">Навчиш</span> — <span class="accent-teal">лишиться</span>. <span class="accent-green">Навчиться</span> — примножиться.',
    heroText:
      "Постійна пам'ять. Структуровані знання. Контекст, що зберігається між усіма сесіями.",
    principleTitle: 'Знання мають накопичуватися — а не випаровуватися.',
    compareBeforeLabel: "Без пам'яті",
    compareAfterLabel: 'Із Soleri',
    compareBefore: `<span class="dim">// Сесія 1</span>
<span class="warn">Ти:</span> Ми використовуємо Tailwind із семантичними токенами,
      ніколи — сирі hex. Базовий крок відступів — 4px.
<span class="warn">AI:</span>  Зрозуміло! Я цього дотримуватимуся.

<span class="dim">// Сесія 2 — наступного дня</span>
<span class="warn">Ти:</span> Чому ти знову використав #3B82F6?
<span class="warn">AI:</span>  Вибач, можеш нагадати мені
      твої домовленості щодо кольорів?

<span class="dim">// Сесія 47 — те саме питання, знову</span>`,
    compareAfter: `<span class="dim">// Сесія 1</span>
<span class="hl">Ти:</span> Ми використовуємо Tailwind із семантичними токенами.
<span class="hl">AI:</span>  Збережено у сховищі. Я це проконтролюю.

<span class="dim">// Сесія 47</span>
<span class="hl">Ти:</span> Переглянь цей компонент.
<span class="hl">AI:</span>  Знайдено 2 сирі hex-значення. У твоєму сховищі зазначено:
      лише семантичні токени. Виправляю.
      <span class="ok">✓ Шаблон застосовано зі сховища</span>
      <span class="ok">✓ Brain strength: 94% (12 сесій)</span>`,
    howTitle: 'Один рушій.<br/>Одне сховище.<br/>Жодної зайвої координації.',
    howText:
      '<strong>Сховище</strong> для знань, <strong>Brain</strong> для навчання, <strong>Memory</strong> для контексту. Один процес. Знання автоматично організуються, векторизуються й накопичуються.',
    engineTags: ['сховище', 'Brain', 'Memory'],
    features: [
      {
        title: 'Конфігурація як код',
        text: 'Одна команда генерує конфіг. Голос, домени, бекенди сховища — усе декларативно й під контролем версій.',
        code: `<span class="cmt"># agent.yaml (generated by create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">direct, technical, thorough</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastructure]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Підключувані пакети знань',
        text: 'npm-пакети, які можна підключити до будь-якого агента. Стартовий та спільнотний пакети безкоштовні.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">вбудовано</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">встановлено</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">встановлено</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">спільне сховище</span>`,
      },
      {
        title: 'Тека = агент',
        text: 'Агент — це тека. Без TypeScript, без збірки. Claude Code читає файли напряму. Рушій забезпечує збереження та навчання.',
        code: `<span class="key">my-agent/</span>           <span class="cmt"># агент — це тека</span>
├── <span class="ok">agent.yaml</span>       <span class="cmt"># ідентичність + конфіг</span>
├── <span class="key">instructions/</span>    <span class="cmt"># правила поведінки</span>
├── <span class="key">workflows/</span>       <span class="cmt"># покрокові плейбуки</span>
├── <span class="key">knowledge/</span>       <span class="cmt"># доменні знання</span>
├── <span class="key">skills/</span>          <span class="cmt"># файли SKILL.md</span>
└── .mcp.json        <span class="cmt"># підключення до рушія</span>`,
      },
      {
        title: 'Холодний старт, а не з нуля',
        text: 'Стартові знання — під час create. Сканування проєкту — під час першого запуску. Далі — керована фіксація.',
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Installed starter knowledge  <span class="val">34 patterns</span>
<span class="ok">✓</span> Scanned project              <span class="val">React + TS</span>
<span class="ok">✓</span> Auto-captured                <span class="val">12 patterns</span>
<span class="ok">✓</span> Vault ready                  <span class="val">46 entries</span>

<span class="cmt"># After 3 sessions:</span>
<span class="warn">Brain:</span> You've fixed this import style 3×.
       <span class="val">Capture as pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Одне сховище. Багато доменів.',
    cards: [
      {
        title: 'Фронтенд',
        domain: 'Домен',
        cls: 'salvador',
        capabilities: ['Патерни React', 'Токени дизайну', "Рев'ю компонентів", 'Доступність'],
        ships: 'Запитай про кнопки — сховище спершу шукає тут.',
      },
      {
        title: 'Бекенд',
        domain: 'Домен',
        cls: 'gaudi',
        capabilities: [
          'Конвенції API',
          'Схеми бази даних',
          'Патерни автентифікації',
          'Продуктивність',
        ],
        ships: 'Запитай про запити чи дизайн API — сховище підтягує звідси.',
      },
      {
        title: 'Наскрізні',
        domain: 'Домен',
        cls: 'sentinel',
        capabilities: ['Робочі процеси Git', "Код-рев'ю", 'Стратегії тестування', 'Документація'],
        ships: "Патерни, що охоплюють домени. Граф автоматично знаходить зв'язки.",
      },
    ],
    terminalTitle: 'Термінал',
    terminalCode: `<span class="comment"># Створення файлового агента (~3 секунди)</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Створено agent.yaml</span>
<span class="comment">  ✓ Згенеровано instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ Автоматично зібрано CLAUDE.md</span>
<span class="comment">  ✓ Готово — без етапу збірки</span>

<span class="comment"># Реєстрація та старт розробки</span>
<span class="prompt">$</span> <span class="cmd">soleri install</span>            <span class="comment"># реєстрація MCP-сервера</span>
<span class="prompt">$</span> <span class="cmd">soleri dev</span>                <span class="comment"># запуск рушія + спостереження за файлами</span>

<span class="comment"># Додайте ще знань</span>
<span class="prompt">$</span> <span class="cmd">soleri pack</span> <span class="arg">install community/react-patterns</span>`,
    archTitle: 'Два шари, чітко розділені',
    archSubtitle:
      'Тека агента — це оболонка. Рушій знань — це мозок. Вони розвиваються незалежно.',
    layers: [
      {
        label: 'Тека агента',
        text: 'Прості файли: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Claude Code читає їх напряму. Без TypeScript, без збірки.',
      },
      {
        label: 'Доменні пакети',
        text: 'Підключувані модулі експертизи. Додавай дизайн-системи, код-рев\'ю або власні домени без зміни теки агента.',
      },
      {
        label: 'Рушій знань',
        text: 'Один MCP-сервер (<code>@soleri/core</code>). Сховище, Brain, Куратор, Планувальник, Пам\'ять. Персистентний стан та навчання. Усі агенти використовують один рушій.',
      },
      {
        label: 'Транспорти',
        text: 'MCP (stdio) для Claude Code та Cursor. HTTP/SSE для дашбордів. WebSocket для стримінгу. Telegram для розмовного доступу.',
      },
    ],
  },
  it: {
    heroTitle:
      'Quello che <span class="accent-amber">insegni</span> resta. Quello che <span class="accent-teal">apprende</span> si accumula.',
    heroText:
      'Memoria persistente. Conoscenza strutturata. Contesto che si mantiene in ogni sessione.',
    principleTitle: 'La conoscenza dovrebbe accumularsi, non evaporare.',
    compareBeforeLabel: 'Senza memoria',
    compareAfterLabel: 'Con Soleri',
    compareBefore: `<span class="dim">// Sessione 1</span>
<span class="warn">Tu:</span> Usiamo Tailwind con token semantici, mai esadecimale puro. Lo spazio è base 4px.
<span class="warn">AI:</span> Capito! Seguirò questo.

<span class="dim">// Sessione 2 — il giorno seguente</span>
<span class="warn">Tu:</span> Perché hai usato di nuovo #3B82F6?
<span class="warn">AI:</span> Scusa, puoi ricordarmi le tue convenzioni sui colori?

<span class="dim">// Sessione 47 — stessa domanda, ancora una volta</span>`,
    compareAfter: `<span class="dim">// Sessione 1</span>
<span class="hl">Tu:</span> Usiamo Tailwind con token semantici.
<span class="hl">AI:</span> Salvato nel Vault. D'ora in poi applicherò questa regola.

<span class="dim">// Sessione 47</span>
<span class="hl">Tu:</span> Rivedi questo componente.
<span class="hl">AI:</span> Ho trovato 2 valori esadecimali grezzi. Il Vault dice: solo token semantici. Correggo subito.
      <span class="ok">✓ Pattern applicato dal Vault</span>
      <span class="ok">✓ Brain strength: 94% (12 sessioni)</span>`,
    howTitle: 'Un motore.<br/>Un vault.<br/>Nessun sovraccarico di coordinamento.',
    howText:
      'Un <strong>Vault</strong> per la conoscenza, un <strong>Cervello</strong> che apprende, una <strong>Memoria</strong> che persiste. Un unico processo. Dagli conoscenza — la organizza, la vettorializza e impara.',
    engineTags: ['Vault', 'Cervello', 'Memoria'],
    features: [
      {
        title: 'Configurazione come codice',
        text: 'Un comando genera la configurazione. Voce, domini, backend del vault — tutto dichiarativo, tutto sotto controllo di versione.',
        code: `<span class="cmt"># agent.yaml (generato da create)</span>
<span class="key">name:</span> <span class="val">my-agent</span>
<span class="key">voice:</span> <span class="val">diretto, tecnico, approfondito</span>
<span class="key">domains:</span> <span class="val">[frontend, backend, infrastruttura]</span>
<span class="key">vault:</span>
  <span class="key">backends:</span>
    - <span class="key">type:</span> <span class="val">local</span>
    - <span class="key">type:</span> <span class="val">git</span>
      <span class="key">uri:</span>  <span class="val">git@github.com:team/vault.git</span>`,
      },
      {
        title: 'Pacchetti di conoscenza modulari',
        text: 'Pacchetti npm che inserisci in qualsiasi agente. I pacchetti Starter e Community sono gratuiti.',
        code: `<span class="cmt">$ soleri packs list</span>
<span class="ok">✓</span> starter/code-review    <span class="val">v1.0.0</span>  <span class="cmt">integrato</span>
<span class="ok">✓</span> community/react        <span class="val">v0.3.0</span>  <span class="cmt">installato</span>
<span class="ok">✓</span> community/typescript   <span class="val">v0.4.0</span>  <span class="cmt">installato</span>
  team/design-standards  <span class="val">v2.1.0</span>  <span class="cmt">vault condiviso</span>`,
      },
      {
        title: 'Cartella = agente',
        text: "Un agente è una cartella. Niente TypeScript, nessun passaggio di build. Claude Code la legge nativamente. Il motore fornisce persistenza e apprendimento.",
        code: `<span class="key">my-agent/</span>           <span class="cmt"># l'agente È la cartella</span>
├── <span class="ok">agent.yaml</span>       <span class="cmt"># identità + configurazione</span>
├── <span class="key">instructions/</span>    <span class="cmt"># regole comportamentali</span>
├── <span class="key">workflows/</span>       <span class="cmt"># playbook passo-passo</span>
├── <span class="key">knowledge/</span>       <span class="cmt"># intelligenza di dominio</span>
├── <span class="key">skills/</span>          <span class="cmt"># file SKILL.md</span>
└── .mcp.json        <span class="cmt"># connessione al motore</span>`,
      },
      {
        title: 'Avvio a freddo, non una lavagna vuota',
        text: "Conoscenza iniziale alla creazione. Scansione del progetto al primo avvio. Poi ti guida nell'onboarding.",
        code: `<span class="cmt">$ soleri create my-agent</span>
<span class="ok">✓</span> Conoscenza iniziale installata  <span class="val">34 pattern</span>
<span class="ok">✓</span> Progetto scansionato              <span class="val">React + TS</span>
<span class="ok">✓</span> Acquisizione automatica                <span class="val">12 pattern</span>
<span class="ok">✓</span> Vault pronto                  <span class="val">46 voci</span>

<span class="cmt"># Dopo 3 sessioni:</span>
<span class="warn">Cervello:</span> Hai corretto questo stile di importazione 3 volte.
       <span class="val">Acquisire come pattern? [y/n]</span>`,
      },
    ],
    cardsTitle: 'Un vault. Molti domini.',
    cards: [
      {
        title: 'Frontend',
        domain: 'Dominio',
        cls: 'salvador',
        capabilities: ['Pattern React', 'Token di design', 'Revisione componenti', 'Accessibilità'],
        ships: 'Chiedi dei pulsanti — il vault cerca qui per primo.',
      },
      {
        title: 'Backend',
        domain: 'Dominio',
        cls: 'gaudi',
        capabilities: [
          'Convenzioni API',
          'Schemi database',
          'Pattern di autenticazione',
          'Prestazioni',
        ],
        ships: 'Chiedi di query o API design — il vault attinge da qui.',
      },
      {
        title: 'Trasversali',
        domain: 'Dominio',
        cls: 'sentinel',
        capabilities: [
          'Flussi di lavoro Git',
          'Revisione del codice',
          'Strategie di test',
          'Documentazione',
        ],
        ships: 'Pattern che attraversano i domini. Il grafo trova connessioni automaticamente.',
      },
    ],
    terminalTitle: 'Terminale',
    terminalCode: `<span class="comment"># Crea un agente file-tree (~3 secondi)</span>
<span class="prompt">$</span> <span class="cmd">soleri create</span> <span class="arg">my-agent</span>

<span class="comment">  ✓ Creato agent.yaml</span>
<span class="comment">  ✓ Generati instructions/, workflows/, knowledge/</span>
<span class="comment">  ✓ CLAUDE.md composto automaticamente</span>
<span class="comment">  ✓ Pronto — nessun passaggio di build</span>

<span class="comment"># Registra e inizia a sviluppare</span>
<span class="prompt">$</span> <span class="cmd">soleri install</span>            <span class="comment"># registra server MCP</span>
<span class="prompt">$</span> <span class="cmd">soleri dev</span>                <span class="comment"># avvia motore + osserva file</span>

<span class="comment"># Alimentalo con più conoscenza</span>
<span class="prompt">$</span> <span class="cmd">soleri pack</span> <span class="arg">install community/react-patterns</span>`,
    archTitle: 'Due livelli, nettamente separati',
    archSubtitle:
      "La cartella dell'agente è il guscio. Il motore di conoscenza è il cervello. Evolvono indipendentemente.",
    layers: [
      {
        label: 'Cartella agente',
        text: 'File semplici: <code>agent.yaml</code>, <code>instructions/</code>, <code>workflows/</code>, <code>knowledge/</code>. Claude Code li legge nativamente. Niente TypeScript, nessun build.',
      },
      {
        label: 'Pacchetti dominio',
        text: "Moduli di competenza collegabili. Aggiungi design system, code review o domini personalizzati senza modificare la cartella dell'agente.",
      },
      {
        label: 'Motore di conoscenza',
        text: 'Un unico server MCP (<code>@soleri/core</code>). Vault, Cervello, Curatore, Pianificatore, Memoria. Stato persistente e apprendimento. Tutti gli agenti condividono un motore.',
      },
      {
        label: 'Trasporti',
        text: 'MCP (stdio) per Claude Code e Cursor. HTTP/SSE per dashboard. WebSocket per streaming. Telegram per accesso conversazionale.',
      },
    ],
  },
};

interface HomeContent {
  heroTitle: string;
  heroText: string;
  principleTitle: string;
  compareBeforeLabel: string;
  compareAfterLabel: string;
  compareBefore: string;
  compareAfter: string;
  howTitle: string;
  howText: string;
  engineTags: string[];
  features: { title: string; text: string; code: string }[];
  cardsTitle: string;
  cards: { title: string; domain: string; cls: string; capabilities: string[]; ships: string }[];
  terminalTitle: string;
  terminalCode: string;
  archTitle: string;
  archSubtitle: string;
  layers: { label: string; text: string }[];
}
